#!/usr/bin/env python3

# SPDX-FileCopyrightText: Copyright 2024-2025 Arm Limited and/or its affiliates <open-source-office@arm.com>

"""This script will generate a list of tests where the expected result in the
source files needs to be overridden via the lit command line or environment
variables.
It can also be used to track where downstream testing diverges from
upstream, and why."""

import argparse
import os
import re
import subprocess

from enum import Enum
from typing import Callable, NamedTuple, List


class NewResult(Enum):
    """Enum storing the potential new result a test."""

    XFAILED = "FAILED"  # Replace a failure with an expected failure.
    PASSED = "PASSED"  # Replace an unexpected pass with a pass.
    EXCLUDE = "EXCLUDE"  # Exclude a test, so that it is not run at all.


class XFail(NamedTuple):
    """Class to collect information about an xfail."""

    name: str  # Name to identify the xfail.
    testnames: List[str]  # The tests to include.
    result: NewResult  # The expected result.
    project: str  # Affected project.
    variants: List[str] = None  # Affected library variants, if applicable.
    conditional: Callable = None  # A function that will test whether an xfail applies.
    issue_link: str = None  # Optional link to a GitHub issue.
    description: str = None  # Optional field for notes.


def main():
    arg_parser = argparse.ArgumentParser(
        prog="xfailgen",
        description="A script that generates lit environment variables to xfail or filter tests.",
    )
    arg_parser.add_argument(
        "--variant",
        help="For library specific projects, the variant being tested.",
    )
    arg_parser.add_argument(
        "--libc",
        help="For library specific projects, the C library that was used.",
    )
    arg_parser.add_argument(
        "--clang",
        help="Path to clang for conditional testing.",
    )
    arg_parser.add_argument(
        "--project",
        required=True,
        help="Project to generate xfails for.",
    )
    arg_parser.add_argument(
        "--output-args",
        help="Write the test lists to a file with --xfail and --xfail-not"
        "parameters, which can be read directly by lit by prefixing with @.",
    )
    args = arg_parser.parse_args()

    # Test whether there is a multilib error from -frwpi
    def check_frwpi_error():
        test_args = [
            args.clang,
            "--print-multi-directory",
            "-target",
            "arm-none-eabi",
            "-frwpi",
        ]
        p = subprocess.run(test_args, capture_output=True, check=False)
        return p.returncode != 0

    # Test whether there is a multilib warning from -mcpu=cortex-r52
    def check_r52_warning():
        test_args = [
            args.clang,
            "--print-multi-directory",
            "-target",
            "arm-none-eabi",
            "-mcpu=cortex-r52",
            "-Werror",
        ]
        p = subprocess.run(test_args, capture_output=True, check=False)
        return p.returncode != 0

    xfails = [
        XFail(
            name="no frwpi",
            testnames=[
                "Driver/ropi-rwpi.c",
                "Preprocessor/arm-pic-predefines.c",
            ],
            result=NewResult.XFAILED,
            conditional=check_frwpi_error,
            project="clang",
            description="The multilib built by ATfE will generate a configuration error if -frwpi is used. Will pass if run before the multilib is installed.",
        ),
        XFail(
            name="no r52",
            testnames=[
                "Driver/arm-fpu-selection.s",
            ],
            result=NewResult.XFAILED,
            conditional=check_r52_warning,
            project="clang",
            description="If the installed default multilib does not have a library available for -mcpu=cortex-r52, this test will fail.",
        ),
        XFail(
            name="emulated crash signals",
            testnames=[
                "aarch64/emupac.c",
            ],
            result=NewResult.XFAILED,
            project="compiler-rt",
            variants=[
                "aarch64a",
                "aarch64a_be",
                "aarch64a_be_exn_rtti",
                "aarch64a_be_soft_nofp",
                "aarch64a_be_soft_nofp_exn_rtti",
                "aarch64a_exn_rtti",
                "aarch64a_exn_rtti_unaligned",
                "aarch64a_soft_nofp",
                "aarch64a_soft_nofp_exn_rtti",
                "aarch64a_unaligned",
                "aarch64r",
                "aarch64r_be",
                "aarch64r_be_exn_rtti",
                "aarch64r_be_soft_nofp",
                "aarch64r_be_soft_nofp_exn_rtti",
                "aarch64r_exn_rtti",
                "aarch64r_exn_rtti_unaligned",
                "aarch64r_soft_nofp",
                "aarch64r_soft_nofp_exn_rtti",
                "aarch64r_soft_nofp_exn_rtti_unaligned",
                "aarch64r_soft_nofp_unaligned",
                "aarch64r_unaligned",
            ],
            description="FVP and QEMU do not support crash signal handling",
        ),
        XFail(
            name="atomics part 1",
            testnames=[
                "extensions/libcxx/atomics/atomics.flag/init_bool.pass.cpp",
                "libcxx/diagnostics/atomic.nodiscard.verify.cpp",
                "libcxx/thread/thread.stoptoken/intrusive_shared_ptr.pass.cpp",
                "libcxx/utilities/utility/mem.res/mem.res.monotonic.buffer/mem.res.monotonic.buffer.mem/allocate_from_underaligned_buffer.pass.cpp",
                "libcxx/utilities/utility/mem.res/mem.res.monotonic.buffer/mem.res.monotonic.buffer.mem/allocate_in_geometric_progression.pass.cpp",
                "libcxx/utilities/utility/mem.res/mem.res.pool/unsynchronized_buffer.pass.cpp",
                "std/atomics/atomics.flag/atomic_flag_clear.pass.cpp",
                "std/atomics/atomics.flag/atomic_flag_clear_explicit.pass.cpp",
                "std/atomics/atomics.flag/atomic_flag_test.pass.cpp",
                "std/atomics/atomics.flag/atomic_flag_test_and_set.pass.cpp",
                "std/atomics/atomics.flag/atomic_flag_test_and_set_explicit.pass.cpp",
                "std/atomics/atomics.flag/atomic_flag_test_explicit.pass.cpp",
                "std/atomics/atomics.flag/clear.pass.cpp",
                "std/atomics/atomics.flag/default.pass.cpp",
                "std/atomics/atomics.flag/init.pass.cpp",
                "std/atomics/atomics.flag/test_and_set.pass.cpp",
                "std/atomics/atomics.general/replace_failure_order.pass.cpp",
                "std/atomics/atomics.ref/address.pass.cpp",
                "std/atomics/atomics.ref/ctor.pass.cpp",
                "std/atomics/atomics.ref/deduction.pass.cpp",
                "std/atomics/atomics.ref/is_always_lock_free.pass.cpp",
                "std/atomics/atomics.types.generic/address.pass.cpp",
                "std/atomics/atomics.types.generic/bool.pass.cpp",
                "std/atomics/atomics.types.generic/standard_layout.compile.pass.cpp",
                "std/atomics/atomics.types.operations/atomics.types.operations.req/atomic_var_init.pass.cpp",
                "std/atomics/atomics.types.operations/atomics.types.operations.req/dtor.pass.cpp",
                "std/atomics/types.pass.cpp",
                "std/containers/container.adaptors/flat.map/flat.map.cons/deduct_pmr.pass.cpp",
                "std/containers/container.adaptors/flat.map/flat.map.cons/pmr.pass.cpp",
                "std/containers/container.adaptors/flat.multimap/flat.multimap.cons/deduct_pmr.pass.cpp",
                "std/containers/container.adaptors/flat.multimap/flat.multimap.cons/pmr.pass.cpp",
                "std/containers/container.adaptors/flat.multiset/flat.multiset.cons/deduct_pmr.pass.cpp",
                "std/containers/container.adaptors/flat.multiset/flat.multiset.cons/pmr.pass.cpp",
                "std/containers/container.adaptors/flat.set/flat.set.cons/deduct_pmr.pass.cpp",
                "std/containers/container.adaptors/flat.set/flat.set.cons/pmr.pass.cpp",
                "std/input.output/string.streams/istringstream/istringstream.members/str.allocator_propagation.pass.cpp",
                "std/input.output/string.streams/ostringstream/ostringstream.members/str.allocator_propagation.pass.cpp",
                "std/input.output/string.streams/stringstream/stringstream.members/str.allocator_propagation.pass.cpp",
                "std/utilities/utility/mem.res/mem.poly.allocator.class/mem.poly.allocator.class.general/equality.pass.cpp",
                "std/utilities/utility/mem.res/mem.poly.allocator.class/mem.poly.allocator.mem/construct_pair.pass.cpp",
                "std/utilities/utility/mem.res/mem.poly.allocator.class/mem.poly.allocator.mem/construct_piecewise_pair_evil.pass.cpp",
                "std/utilities/utility/mem.res/mem.poly.allocator.class/mem.poly.allocator.mem/destroy.pass.cpp",
                "std/utilities/utility/mem.res/mem.poly.allocator.class/mem.poly.allocator.mem/resource.pass.cpp",
                "std/utilities/utility/mem.res/mem.poly.allocator.class/mem.poly.allocator.mem/select_on_container_copy_construction.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.aliases/header_deque_synop.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.aliases/header_deque_synop2.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.aliases/header_forward_list_synop.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.aliases/header_list_synop.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.aliases/header_list_synop2.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.aliases/header_map_synop.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.aliases/header_map_synop2.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.aliases/header_regex_synop.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.aliases/header_set_synop.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.aliases/header_set_synop2.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.aliases/header_string_synop.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.aliases/header_string_synop2.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.aliases/header_unordered_map_synop.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.aliases/header_unordered_map_synop2.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.aliases/header_unordered_set_synop.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.aliases/header_unordered_set_synop2.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.aliases/header_vector_synop.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.aliases/header_vector_synop2.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.global/new_delete_resource.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.global/null_memory_resource.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.monotonic.buffer/mem.res.monotonic.buffer.ctor/with_default_resource.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.monotonic.buffer/mem.res.monotonic.buffer.ctor/without_buffer.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.monotonic.buffer/mem.res.monotonic.buffer.mem/allocate_deallocate.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.monotonic.buffer/mem.res.monotonic.buffer.mem/allocate_from_initial_buffer.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.monotonic.buffer/mem.res.monotonic.buffer.mem/allocate_from_zero_sized_buffer.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.monotonic.buffer/mem.res.monotonic.buffer.mem/allocate_mem.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.monotonic.buffer/mem.res.monotonic.buffer.mem/allocate_overaligned_request.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.monotonic.buffer/mem.res.monotonic.buffer.mem/allocate_with_initial_size.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.monotonic.buffer/mem.res.monotonic.buffer.mem/equality.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.monotonic.buffer/mem.res.monotonic.buffer.mem/release_reset_initial_status.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.pool/mem.res.pool.ctor/ctor_does_not_allocate.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.pool/mem.res.pool.ctor/sync_with_default_resource.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.pool/mem.res.pool.ctor/unsync_with_default_resource.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.pool/mem.res.pool.mem/equality.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.pool/mem.res.pool.mem/sync_allocate.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.pool/mem.res.pool.mem/sync_allocate_overaligned_request.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.pool/mem.res.pool.mem/sync_allocate_reuse_blocks.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.pool/mem.res.pool.mem/unsync_allocate.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.pool/mem.res.pool.mem/unsync_allocate_overaligned_request.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.pool/mem.res.pool.mem/unsync_allocate_reuse_blocks.pass.cpp",
            ],
            result=NewResult.XFAILED,
            project="libcxx",
            variants=[
                "armv4t_exn_rtti_size",
                "armv4t_size",
                "armv5te_exn_rtti_size",
                "armv5te_size",
                "armv6m_soft_nofp_exn_rtti_size",
                "armv6m_soft_nofp_size",
                "armebv6m_soft_nofp_size",
                "armebv6m_soft_nofp_exn_rtti_size",
            ],
            description="pmr missing or incomplete pstl",
        ),
        XFail(
            name="atomics part 2",
            testnames=[
                "libcxx/utilities/utility/mem.res/mem.poly.allocator.class/mem.poly.allocator.mem/construct_piecewise_pair.pass.cpp",
                "std/utilities/utility/mem.res/mem.poly.allocator.class/mem.poly.allocator.ctor/default.pass.cpp",
                "std/utilities/utility/mem.res/mem.poly.allocator.class/mem.poly.allocator.ctor/memory_resource_convert.pass.cpp",
                "std/utilities/utility/mem.res/mem.poly.allocator.class/mem.poly.allocator.eq/equal.pass.cpp",
                "std/utilities/utility/mem.res/mem.poly.allocator.class/mem.poly.allocator.eq/not_equal.pass.cpp",
                "std/utilities/utility/mem.res/mem.poly.allocator.class/mem.poly.allocator.mem/allocate.pass.cpp",
                "std/utilities/utility/mem.res/mem.poly.allocator.class/mem.poly.allocator.mem/allocate_deallocate_bytes.pass.cpp",
                "std/utilities/utility/mem.res/mem.poly.allocator.class/mem.poly.allocator.mem/allocate_deallocate_object.pass.cpp",
                "std/utilities/utility/mem.res/mem.poly.allocator.class/mem.poly.allocator.mem/construct_pair_const_lvalue_pair.pass.cpp",
                "std/utilities/utility/mem.res/mem.poly.allocator.class/mem.poly.allocator.mem/construct_pair_rvalue.pass.cpp",
                "std/utilities/utility/mem.res/mem.poly.allocator.class/mem.poly.allocator.mem/construct_pair_values.pass.cpp",
                "std/utilities/utility/mem.res/mem.poly.allocator.class/mem.poly.allocator.mem/construct_piecewise_pair.pass.cpp",
                "std/utilities/utility/mem.res/mem.poly.allocator.class/mem.poly.allocator.mem/construct_types.pass.cpp",
                "std/utilities/utility/mem.res/mem.poly.allocator.class/mem.poly.allocator.mem/deallocate.pass.cpp",
                "std/utilities/utility/mem.res/mem.poly.allocator.class/mem.poly.allocator.mem/new_delete_object.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.global/default_resource.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.monotonic.buffer/mem.res.monotonic.buffer.mem/allocate_exception_safety.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.pool/mem.res.pool.mem/sync_deallocate_matches_allocate.pass.cpp",
                "std/utilities/utility/mem.res/mem.res.pool/mem.res.pool.mem/unsync_deallocate_matches_allocate.pass.cpp",
                "std/utilities/utility/mem.res/mem.res/mem.res.eq/equal.pass.cpp",
                "std/utilities/utility/mem.res/mem.res/mem.res.eq/not_equal.pass.cpp",
                "std/utilities/utility/mem.res/mem.res/mem.res.public/allocate.pass.cpp",
                "std/utilities/utility/mem.res/mem.res/mem.res.public/deallocate.pass.cpp",
                "std/utilities/utility/mem.res/mem.res/mem.res.public/dtor.pass.cpp",
                "std/utilities/utility/mem.res/mem.res/mem.res.public/is_equal.pass.cpp",
            ],
            result=NewResult.XFAILED,
            project="libcxx",
            variants=[
                "armv4t_exn_rtti_size",
                "armv5te_exn_rtti_size",
                "armv6m_soft_nofp_exn_rtti_size",
                "armebv6m_soft_nofp_size",
                "armebv6m_soft_nofp_exn_rtti_size",
            ],
            description="pmr missing or incomplete pstl",
        ),
        XFail(
            name="atomics part 3",
            testnames=[
                "std/atomics/atomics.fences/atomic_signal_fence.pass.cpp",
                "std/atomics/atomics.fences/atomic_thread_fence.pass.cpp",
            ],
            result=NewResult.XFAILED,
            project="libcxx",
            variants=[
                "armv4t_exn_rtti_size",
                "armv4t_size",
                "armv5te_exn_rtti_size",
                "armv5te_size",
            ],
            description="pmr missing or incomplete pstl",
        ),
        XFail(
            name="atomics part 4",
            testnames=[
                "std/atomics/atomics.types.generic/cas_non_power_of_2.pass.cpp",
            ],
            result=NewResult.XFAILED,
            project="libcxx",
            variants=[
                "armv4t_exn_rtti_size",
                "armv4t_size",
                "armv5te_exn_rtti_size",
                "armv5te_size",
                "armv6m_soft_nofp_exn_rtti_size",
                "armv6m_soft_nofp_size",
                "armebv6m_soft_nofp_exn_rtti_size",
                "armebv6m_soft_nofp_size",
                "armv7m_hard_fpv4_sp_d16_exn_rtti_size",
                "armv7m_hard_fpv4_sp_d16_exn_rtti_unaligned_size",
                "armv7m_hard_fpv4_sp_d16_size",
                "armv7m_hard_fpv4_sp_d16_unaligned_size",
                "armv7m_hard_fpv5_d16_exn_rtti_unaligned_size",
                "armv7m_hard_fpv5_d16_unaligned_size",
                "armv7m_soft_fpv4_sp_d16_exn_rtti_size",
                "armv7m_soft_fpv4_sp_d16_exn_rtti_unaligned_size",
                "armv7m_soft_fpv4_sp_d16_size",
                "armv7m_soft_fpv4_sp_d16_unaligned_size",
                "armv7m_soft_nofp_exn_rtti_size",
                "armv7m_soft_nofp_exn_rtti_unaligned_size",
                "armv7m_soft_nofp_size",
                "armv7m_soft_nofp_unaligned_size",
                "armebv7m_hard_fpv4_sp_d16_exn_rtti_size",
                "armebv7m_hard_fpv4_sp_d16_size",
                "armebv7m_soft_fpv4_sp_d16_exn_rtti_size",
                "armebv7m_soft_fpv4_sp_d16_size",
                "armebv7m_soft_nofp_exn_rtti_size",
                "armebv7m_soft_nofp_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_exn_rtti_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_unaligned_size",
                "armv8.1m.main_hard_fp_nomve_pacret_bti_exn_rtti_size",
                "armv8.1m.main_hard_fp_nomve_pacret_bti_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_fp_nomve_pacret_bti_size",
                "armv8.1m.main_soft_nofp_nomve_pacret_bti_size",
                "armv8.1m.main_soft_nofp_nomve_pacret_bti_unaligned_size",
                "armv8.1m.main_soft_nofp_nomve_pacret_bti_exn_rtti_size",
                "armv8.1m.main_soft_nofp_nomve_pacret_bti_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_fp_nomve_pacret_bti_unaligned_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_unaligned_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_exn_rtti_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_exn_rtti_unaligned_size",
            ],
            description="target lacks hardware CAS for non-power-of-two atomic object sizes",
        ),
        XFail(
            name="alg.exponential",
            testnames=[
                "std/re/re.alg/re.alg.match/exponential.pass.cpp",
                "std/re/re.alg/re.alg.search/exponential.pass.cpp",
            ],
            result=NewResult.XFAILED,
            project="libcxx",
            variants=[
                "armv6m_soft_nofp_exn_rtti_size",
                "armv7m_hard_fpv4_sp_d16_exn_rtti_size",
                "armv7m_hard_fpv4_sp_d16_exn_rtti_unaligned_size",
                "armv7m_hard_fpv5_d16_exn_rtti_unaligned_size",
                "armv7m_soft_fpv4_sp_d16_exn_rtti_size",
                "armv7m_soft_fpv4_sp_d16_exn_rtti_unaligned_size",
                "armv7m_soft_nofp_exn_rtti_size",
                "armv7m_soft_nofp_exn_rtti_unaligned_size",
            ],
            description="test too large for embedded targets",
        ),
        XFail(
            name="at_exit",
            testnames=[
                "std/language.support/support.start.term/quick_exit.pass.cpp",
            ],
            result=NewResult.XFAILED,
            project="libcxx",
            description="at_quick_exit symbol is not found",
        ),
        XFail(
            name="demangle",
            testnames=[
                "test_demangle.pass.cpp",
            ],
            result=NewResult.PASSED,
            project="libcxx",
            variants=[
                "aarch64a_unaligned",
                "aarch64a_exn_rtti_unaligned",
                "aarch64a_soft_nofp",
                "aarch64a_soft_nofp_exn_rtti",
                "armebv6m_soft_nofp_exn_rtti_size",
                "armebv6m_soft_nofp_size",
                "armebv7a_hard_vfpv3_d16",
                "armebv7a_hard_vfpv3_d16_exn_rtti",
                "armebv7a_soft_nofp",
                "armebv7a_soft_nofp_exn_rtti",
                "armebv7a_soft_vfpv3_d16",
                "armebv7a_soft_vfpv3_d16_exn_rtti",
                "armebv7m_hard_fpv4_sp_d16_exn_rtti_size",
                "armebv7m_hard_fpv4_sp_d16_size",
                "armebv7m_soft_fpv4_sp_d16_exn_rtti_size",
                "armebv7m_soft_fpv4_sp_d16_size",
                "armebv7m_soft_nofp_exn_rtti_size",
                "armebv7m_soft_nofp_size",
                "armv4t_exn_rtti_size",
                "armv4t_size",
                "armv5te_exn_rtti_size",
                "armv5te_size",
                "armv6m_soft_nofp_exn_rtti_size",
                "armv6m_soft_nofp_size",
                "armv7a_hard_vfpv3_d16",
                "armv7a_hard_vfpv3_d16_exn_rtti",
                "armv7a_hard_vfpv3_d16_exn_rtti_unaligned",
                "armv7a_hard_vfpv3_d16_unaligned",
                "armv7a_soft_nofp",
                "armv7a_soft_nofp_exn_rtti",
                "armv7a_soft_nofp_exn_rtti_unaligned",
                "armv7a_soft_nofp_unaligned",
                "armv7a_soft_vfpv3_d16",
                "armv7a_soft_vfpv3_d16_exn_rtti",
                "armv7a_soft_vfpv3_d16_exn_rtti_unaligned",
                "armv7a_soft_vfpv3_d16_unaligned",
                "armv7m_hard_fpv4_sp_d16_exn_rtti_size",
                "armv7m_hard_fpv4_sp_d16_exn_rtti_unaligned_size",
                "armv7m_hard_fpv4_sp_d16_size",
                "armv7m_hard_fpv4_sp_d16_unaligned_size",
                "armv7m_hard_fpv5_d16_exn_rtti_unaligned_size",
                "armv7m_hard_fpv5_d16_unaligned_size",
                "armv7m_soft_fpv4_sp_d16_exn_rtti_size",
                "armv7m_soft_fpv4_sp_d16_exn_rtti_unaligned_size",
                "armv7m_soft_fpv4_sp_d16_size",
                "armv7m_soft_fpv4_sp_d16_unaligned_size",
                "armv7m_soft_nofp_exn_rtti_size",
                "armv7m_soft_nofp_exn_rtti_unaligned_size",
                "armv7m_soft_nofp_size",
                "armv7m_soft_nofp_unaligned_size",
                "armv7r_hard_vfpv3_d16",
                "armv7r_hard_vfpv3_d16_exn_rtti",
                "armv7r_hard_vfpv3_d16_exn_rtti_unaligned",
                "armv7r_hard_vfpv3_d16_unaligned",
                "armv7r_hard_vfpv3xd",
                "armv7r_hard_vfpv3xd_exn_rtti",
                "armv7r_hard_vfpv3xd_exn_rtti_unaligned",
                "armv7r_hard_vfpv3xd_unaligned",
                "armv7r_soft_nofp",
                "armv7r_soft_nofp_exn_rtti",
                "armv7r_soft_nofp_exn_rtti_unaligned",
                "armv7r_soft_nofp_unaligned",
                "armv7r_soft_vfpv3xd",
                "armv7r_soft_vfpv3xd_exn_rtti",
                "armv7r_soft_vfpv3xd_exn_rtti_unaligned",
                "armv7r_soft_vfpv3xd_unaligned",
                "armv8.1m.main_hard_fp_nomve_exn_rtti_unaligned",
                "armv8.1m.main_hard_fp_nomve_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_fp_nomve_pacret_bti_exn_rtti_size",
                "armv8.1m.main_hard_fp_nomve_pacret_bti_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_fp_nomve_pacret_bti_size",
                "armv8.1m.main_hard_fp_nomve_pacret_bti_unaligned_size",
                "armv8.1m.main_hard_fp_nomve_unaligned",
                "armv8.1m.main_hard_fp_nomve_unaligned_size",
                "armv8.1m.main_hard_fpdp_nomve_exn_rtti_unaligned",
                "armv8.1m.main_hard_fpdp_nomve_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_exn_rtti_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_exn_rtti_unaligned",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_unaligned_size",
                "armv8.1m.main_hard_fpdp_nomve_unaligned",
                "armv8.1m.main_hard_fpdp_nomve_unaligned_size",
                "armv8.1m.main_hard_nofp_mve_exn_rtti_size",
                "armv8.1m.main_hard_nofp_mve_exn_rtti_unaligned",
                "armv8.1m.main_hard_nofp_mve_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_exn_rtti_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_unaligned_size",
                "armv8.1m.main_hard_nofp_mve_size",
                "armv8.1m.main_hard_nofp_mve_unaligned",
                "armv8.1m.main_hard_nofp_mve_unaligned_size",
                "armv8.1m.main_soft_nofp_nomve_exn_rtti_unaligned_size",
                "armv8.1m.main_soft_nofp_nomve_pacret_bti_exn_rtti_size",
                "armv8.1m.main_soft_nofp_nomve_pacret_bti_exn_rtti_unaligned",
                "armv8.1m.main_soft_nofp_nomve_pacret_bti_exn_rtti_unaligned_size",
                "armv8.1m.main_soft_nofp_nomve_pacret_bti_size",
                "armv8.1m.main_soft_nofp_nomve_pacret_bti_unaligned_size",
                "armv8.1m.main_soft_nofp_nomve_unaligned_size",
                "armv8m.main_hard_fp_exn_rtti_unaligned_size",
                "armv8m.main_hard_fp_unaligned_size",
                "armv8m.main_soft_nofp_exn_rtti_unaligned_size",
                "armv8m.main_soft_nofp_unaligned_size",
            ],
            description="Previously xfailed for being too large/slow, but is now passing.",
        ),
        XFail(
            name="demangle-fvp",
            testnames=[
                "test_demangle.pass.cpp",
            ],
            result=NewResult.XFAILED,
            project="libcxx",
            variants=[
                "aarch64a",
                "aarch64a_exn_rtti",
                "aarch64a_be",
                "aarch64a_be_exn_rtti",
                "aarch64a_be_soft_nofp",
                "aarch64a_be_soft_nofp_exn_rtti",
                "aarch64r",
                "aarch64r_unaligned",
                "aarch64r_soft_nofp",
                "aarch64r_soft_nofp_unaligned",
                "aarch64r_soft_nofp_exn_rtti",
                "aarch64r_soft_nofp_exn_rtti_unaligned",
                "aarch64r_be",
                "aarch64r_exn_rtti",
                "aarch64r_exn_rtti_unaligned",
                "aarch64r_be_exn_rtti",
                "aarch64r_be_soft_nofp",
                "aarch64r_be_soft_nofp_exn_rtti",
                "aarch64r_be_soft_nofp_exn_rtti_unaligned",
            ],
            description="FP literal test failure due to truncated long double exponent",
        ),
        XFail(
            name="uchar types",
            testnames=[
                "std/depr/depr.c.headers/uchar_h.compile.pass.cpp",
                "std/strings/c.strings/cuchar.compile.pass.cpp",
            ],
            result=NewResult.PASSED,
            project="libcxx",
            description="More recent picolibc versions do now support char16_t and char32_t",
        ),
        XFail(
            name="picolibc_UID0_lookup",
            testnames=[
                "test-pwd.test",
                "test-grp.test",
            ],
            result=NewResult.EXCLUDE,
            project="picolibc",
            description="UID 0 lookup returning Null on MacOS",
        ),
        XFail(
            name="fstream assert",
            testnames=[
                "std/input.output/file.streams/fstreams/filebuf.virtuals/seekoff.pass.cpp",
                "std/input.output/file.streams/fstreams/filebuf.virtuals/setbuf.pass.cpp",
                "std/input.output/file.streams/fstreams/filebuf.virtuals/xsputn.pass.cpp",
                "std/input.output/file.streams/fstreams/ifstream.members/buffered_reads.pass.cpp",
                "std/input.output/file.streams/fstreams/ofstream.members/buffered_writes.pass.cpp",
            ],
            result=NewResult.XFAILED,
            project="libcxx",
            variants=[
                "aarch64a",
                "aarch64a_exn_rtti",
                "aarch64a_be",
                "aarch64a_be_exn_rtti",
                "aarch64a_be_soft_nofp",
                "aarch64a_be_soft_nofp_exn_rtti",
                "aarch64r",
                "aarch64r_unaligned",
                "aarch64r_exn_rtti",
                "aarch64r_exn_rtti_unaligned",
                "aarch64r_soft_nofp",
                "aarch64r_soft_nofp_unaligned",
                "aarch64r_soft_nofp_exn_rtti",
                "aarch64r_soft_nofp_exn_rtti_unaligned",
                "aarch64r_be",
                "aarch64r_be_exn_rtti",
                "aarch64r_be_soft_nofp",
                "aarch64r_be_soft_nofp_exn_rtti",
                "armebv7a_soft_nofp",
                "armebv7a_soft_nofp_exn_rtti",
                "armebv7a_soft_vfpv3_d16",
                "armebv7a_soft_vfpv3_d16_exn_rtti",
                "armebv7a_hard_vfpv3_d16",
                "armebv7a_hard_vfpv3_d16_exn_rtti",
                "armebv6m_soft_nofp_size",
                "armebv6m_soft_nofp_exn_rtti_size",
                "armebv7m_soft_nofp_size",
                "armebv7m_soft_nofp_exn_rtti_size",
                "armebv7m_soft_fpv4_sp_d16_size",
                "armebv7m_soft_fpv4_sp_d16_exn_rtti_size",
                "armebv7m_hard_fpv4_sp_d16_size",
                "armebv7m_hard_fpv4_sp_d16_exn_rtti_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_unaligned_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_exn_rtti_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_size",
                "armv8.1m.main_hard_fp_nomve_pacret_bti_size",
                "armv8.1m.main_hard_fp_nomve_pacret_bti_exn_rtti_size",
                "armv8.1m.main_hard_fp_nomve_pacret_bti_unaligned_size",
                "armv8.1m.main_hard_fp_nomve_pacret_bti_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_exn_rtti_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_unaligned_size",
                "armv8.1m.main_soft_nofp_nomve_pacret_bti_exn_rtti_size",
                "armv8.1m.main_soft_nofp_nomve_pacret_bti_exn_rtti_unaligned_size",
                "armv8.1m.main_soft_nofp_nomve_pacret_bti_size",
                "armv8.1m.main_soft_nofp_nomve_pacret_bti_unaligned_size",
            ],
            description="fstream assertion failures (seekoff/setbuf/xsputn/buffered IO.",
        ),
        XFail(
            name="128strconv part 1",
            testnames=[
                "std/strings/string.conversions/stold.pass.cpp",
                "std/strings/string.conversions/to_string.pass.cpp",
            ],
            result=NewResult.XFAILED,
            project="libcxx",
            variants=[
                "aarch64a",
                "aarch64a_exn_rtti",
                "aarch64a_unaligned",
                "aarch64a_soft_nofp",
                "aarch64a_soft_nofp_exn_rtti",
                "aarch64a_be",
                "aarch64a_be_exn_rtti",
                "aarch64a_be_soft_nofp",
                "aarch64a_be_soft_nofp_exn_rtti",
                "aarch64r",
                "aarch64r_unaligned",
                "aarch64r_exn_rtti",
                "aarch64r_exn_rtti_unaligned",
                "aarch64r_soft_nofp",
                "aarch64r_soft_nofp_exn_rtti",
                "aarch64r_soft_nofp_unaligned",
                "aarch64r_soft_nofp_exn_rtti_unaligned",
                "aarch64r_be",
                "aarch64r_be_exn_rtti",
                "aarch64r_be_soft_nofp",
                "aarch64r_be_soft_nofp_exn_rtti",
            ],
            description="Broken conversion between 128-bit types and string.",
        ),
        XFail(
            name="128strconv part 2",
            testnames=[
                "std/input.output/iostream.format/output.streams/ostream.formatted/ostream.inserters.arithmetic/long_double.pass.cpp",
                "std/localization/locale.categories/category.monetary/locale.money.get/locale.money.get.members/get_long_double_overlong.pass.cpp",
                "std/localization/locale.categories/category.numeric/locale.nm.put/facet.num.put.members/put_long_double.pass.cpp",
            ],
            result=NewResult.XFAILED,
            project="libcxx",
            variants=[
                "aarch64a",
                "aarch64a_exn_rtti",
                "aarch64a_be",
                "aarch64a_be_exn_rtti",
                "aarch64a_be_soft_nofp",
                "aarch64a_be_soft_nofp_exn_rtti",
                "aarch64r_be",
                "aarch64r_be_exn_rtti",
                "aarch64r_be_soft_nofp",
                "aarch64r_be_soft_nofp_exn_rtti",
                "aarch64r",
                "aarch64r_unaligned",
                "aarch64r_exn_rtti",
                "aarch64r_exn_rtti_unaligned",
                "aarch64r_soft_nofp",
                "aarch64r_soft_nofp_unaligned",
                "aarch64r_soft_nofp_exn_rtti",
                "aarch64r_soft_nofp_exn_rtti_unaligned",
            ],
            description="Broken conversion between 128-bit types and string.",
        ),
        XFail(
            name="128strconv part 3",
            testnames=[
                "std/localization/locale.categories/category.numeric/locale.nm.put/facet.num.put.members/put_long_double.hex.pass.cpp",
            ],
            result=NewResult.XFAILED,
            project="libcxx",
            variants=[
                "aarch64a",
                "aarch64a_exn_rtti",
                "aarch64a_be",
                "aarch64a_be_exn_rtti",
                "aarch64a_exn_rtti",
                "aarch64r_be",
                "aarch64r_be_exn_rtti",
                "aarch64r",
                "aarch64r_unaligned",
                "aarch64r_exn_rtti",
                "aarch64r_exn_rtti_unaligned",
                "aarch64r_soft_nofp",
                "aarch64r_soft_nofp_unaligned",
                "aarch64r_soft_nofp_exn_rtti",
                "aarch64r_soft_nofp_exn_rtti_unaligned",
            ],
            description="Broken conversion between 128-bit types and string.",
        ),
        XFail(
            name="regex exponential abort",
            testnames=[
                "std/re/re.alg/re.alg.match/exponential.pass.cpp",
                "std/re/re.alg/re.alg.search/exponential.pass.cpp",
            ],
            result=NewResult.XFAILED,
            project="libcxx",
            variants=[
                "aarch64a_exn_rtti",
                "aarch64a_exn_rtti_unaligned",
                "aarch64a_soft_nofp_exn_rtti",
                "aarch64a_be_exn_rtti",
                "aarch64a_be_soft_nofp_exn_rtti",
                "aarch64r_exn_rtti",
                "aarch64r_exn_rtti_unaligned",
                "aarch64r_soft_nofp_exn_rtti",
                "aarch64r_soft_nofp_exn_rtti_unaligned",
                "aarch64r_be_exn_rtti",
                "aarch64r_be_soft_nofp_exn_rtti",
                "armv8m.main_soft_nofp_exn_rtti_unaligned_size",
            ],
            description="std::regex exponential match/search tests abort at runtime (exit status 134).",
        ),
        XFail(
            name="sqrt precision on softnofp",
            testnames=[
                "std/numerics/c.math/cmath.pass.cpp",
            ],
            result=NewResult.XFAILED,
            project="libcxx",
            variants=[
                "aarch64a_soft_nofp",
                "aarch64a_soft_nofp_exn_rtti",
                "aarch64a_be_soft_nofp",
                "aarch64a_be_soft_nofp_exn_rtti",
                "aarch64r_soft_nofp",
                "aarch64r_soft_nofp_unaligned",
                "aarch64r_soft_nofp_exn_rtti",
                "aarch64r_soft_nofp_exn_rtti_unaligned",
                "aarch64r_be_soft_nofp",
                "aarch64r_be_soft_nofp_exn_rtti",
            ],
            description="std::sqrt with long double gives incorrect results in soft nofp builds.",
        ),
        XFail(
            name="semihosting tick frequency on Corstone-310 ",
            testnames=[
                "std/time/time.clock/time.clock.file/now.pass.cpp",
                "std/time/time.clock/time.clock.hires/now.pass.cpp",
                "std/time/time.clock/time.clock.system/now.pass.cpp",
            ],
            result=NewResult.XFAILED,
            project="libcxx",
            variants=[
                "armebv6m_soft_nofp_exn_rtti_size",
                "armebv6m_soft_nofp_size",
                "armebv7m_hard_fpv4_sp_d16_exn_rtti_size",
                "armebv7m_hard_fpv4_sp_d16_size",
                "armebv7m_soft_fpv4_sp_d16_exn_rtti_size",
                "armebv7m_soft_fpv4_sp_d16_size",
                "armebv7m_soft_nofp_exn_rtti_size",
                "armebv7m_soft_nofp_size",
                "armv8.1m.main_hard_fp_nomve_pacret_bti_exn_rtti_size",
                "armv8.1m.main_hard_fp_nomve_pacret_bti_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_exn_rtti_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_fp_nomve_pacret_bti_size",
                "armv8.1m.main_hard_fp_nomve_pacret_bti_unaligned_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_unaligned_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_exn_rtti_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_unaligned_size",
                "armv8.1m.main_soft_nofp_nomve_pacret_bti_exn_rtti_size",
                "armv8.1m.main_soft_nofp_nomve_pacret_bti_exn_rtti_unaligned_size",
                "armv8.1m.main_soft_nofp_nomve_pacret_bti_size",
                "armv8.1m.main_soft_nofp_nomve_pacret_bti_unaligned_size",
            ],
            description="semihosting tick frequency issues in Corstone-310 FVP (SDDKW-94045).",
        ),
        XFail(
            name="alloca undeclared error",
            testnames=[
                "aarch64_za_unwind.pass.cpp",
            ],
            result=NewResult.XFAILED,
            project="libcxx",
            variants=[
                "aarch64a",
                "aarch64a_exn_rtti",
                "aarch64a_be",
                "aarch64a_be_exn_rtti",
                "aarch64a_be_soft_nofp",
                "aarch64a_be_soft_nofp_exn_rtti",
                "aarch64r",
                "aarch64r_unaligned",
                "aarch64r_soft_nofp",
                "aarch64r_soft_nofp_unaligned",
                "aarch64r_soft_nofp_exn_rtti",
                "aarch64r_soft_nofp_exn_rtti_unaligned",
                "aarch64r_exn_rtti",
                "aarch64r_exn_rtti_unaligned",
                "aarch64r_be",
                "aarch64r_be_exn_rtti",
                "aarch64r_be_soft_nofp",
                "aarch64r_be_soft_nofp_exn_rtti",
            ],
            description="Test uses alloca() without checking availability or including <alloca.h>.",
        ),
        XFail(
            name="Sync Fault On AArch64 FVP",
            testnames=[
                "unwind_leaffunction.pass.cpp",
            ],
            result=NewResult.XFAILED,
            project="libcxx",
            variants=[
                "aarch64a",
                "aarch64a_exn_rtti",
                "aarch64a_be",
                "aarch64a_be_exn_rtti",
                "aarch64a_be_soft_nofp",
                "aarch64a_be_soft_nofp_exn_rtti",
                "aarch64r",
                "aarch64r_unaligned",
                "aarch64r_soft_nofp",
                "aarch64r_soft_nofp_unaligned",
                "aarch64r_soft_nofp_exn_rtti",
                "aarch64r_soft_nofp_exn_rtti_unaligned",
                "aarch64r_exn_rtti",
                "aarch64r_exn_rtti_unaligned",
                "aarch64r_be",
                "aarch64r_be_exn_rtti",
                "aarch64r_be_soft_nofp",
                "aarch64r_be_soft_nofp_exn_rtti",
            ],
            description="A synchronous fault during execution on AArch64 FVP.",
        ),
        XFail(
            name="Hard Fault On Armv8.1m.main",
            testnames=[
                "unw_resume.pass.cpp",
            ],
            result=NewResult.XFAILED,
            project="libcxx",
            variants=[
                "armv8.1m.main_hard_fp_nomve_pacret_bti_exn_rtti_size",
                "armv8.1m.main_hard_fp_nomve_pacret_bti_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_fp_nomve_pacret_bti_size",
                "armv8.1m.main_hard_fp_nomve_pacret_bti_unaligned_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_exn_rtti_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_unaligned_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_exn_rtti_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_unaligned_size",
                "armv8.1m.main_soft_nofp_nomve_pacret_bti_exn_rtti_size",
                "armv8.1m.main_soft_nofp_nomve_pacret_bti_exn_rtti_unaligned_size",
                "armv8.1m.main_soft_nofp_nomve_pacret_bti_size",
                "armv8.1m.main_soft_nofp_nomve_pacret_bti_unaligned_size",
            ],
            description="A hard fault is observed during execution on Corstone-310 FVP targeting Armv8.1-M.",
        ),
        XFail(
            name="picolibc_sys_seek",
            testnames=[
                "semihost-seek.test",
                "test-fread-fwrite.test",
                "test-posix-io.test",
            ],
            result=NewResult.XFAILED,
            project="picolibc",
            variants=[
                "aarch64a_be_exn_rtti",
                "aarch64a_be_soft_nofp_exn_rtti",
                "aarch64a_be_soft_nofp",
                "aarch64a_be",
                "aarch64a_exn_rtti",
                "aarch64a",
                "aarch64r_be_exn_rtti",
                "aarch64r_be_soft_nofp_exn_rtti",
                "aarch64r_be_soft_nofp",
                "aarch64r_be",
                "aarch64r_exn_rtti_unaligned",
                "aarch64r_exn_rtti",
                "aarch64r_soft_nofp_exn_rtti_unaligned",
                "aarch64r_soft_nofp_exn_rtti",
                "aarch64r_soft_nofp_unaligned",
                "aarch64r_soft_nofp",
                "aarch64r_unaligned",
                "aarch64r",
                "armebv6m_soft_nofp_exn_rtti_size",
                "armebv6m_soft_nofp_size",
                "armebv7a_hard_vfpv3_d16_exn_rtti",
                "armebv7a_hard_vfpv3_d16",
                "armebv7a_soft_nofp_exn_rtti",
                "armebv7a_soft_nofp",
                "armebv7a_soft_vfpv3_d16_exn_rtti",
                "armebv7a_soft_vfpv3_d16",
                "armebv7m_hard_fpv4_sp_d16_exn_rtti_size",
                "armebv7m_hard_fpv4_sp_d16_size",
                "armebv7m_soft_fpv4_sp_d16_exn_rtti_size",
                "armebv7m_soft_fpv4_sp_d16_size",
                "armebv7m_soft_nofp_exn_rtti_size",
                "armebv7m_soft_nofp_size",
                "armv8.1m.main_hard_fp_nomve_pacret_bti_exn_rtti_size",
                "armv8.1m.main_hard_fp_nomve_pacret_bti_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_fp_nomve_pacret_bti_size",
                "armv8.1m.main_hard_fp_nomve_pacret_bti_unaligned_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_exn_rtti_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_unaligned_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_exn_rtti_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_unaligned_size",
                "armv8.1m.main_soft_nofp_nomve_pacret_bti_exn_rtti_size",
                "armv8.1m.main_soft_nofp_nomve_pacret_bti_exn_rtti_unaligned_size",
                "armv8.1m.main_soft_nofp_nomve_pacret_bti_size",
                "armv8.1m.main_soft_nofp_nomve_pacret_bti_unaligned_size",
            ],
            description="SYS_SEEK returns wrong value when using FVPs (SDDKW-25808).",
        ),
        XFail(
            name="picolibc_rateInHz",
            testnames=[
                "semihost-gettimeofday.test",
                "test-stat.test",
                "test-posix-time.test",
            ],
            result=NewResult.XFAILED,
            project="picolibc",
            variants=[
                "armebv6m_soft_nofp_exn_rtti_size",
                "armebv6m_soft_nofp_size",
                "armebv7m_hard_fpv4_sp_d16_exn_rtti_size",
                "armebv7m_hard_fpv4_sp_d16_size",
                "armebv7m_soft_fpv4_sp_d16_exn_rtti_size",
                "armebv7m_soft_fpv4_sp_d16_size",
                "armebv7m_soft_nofp_exn_rtti_size",
                "armebv7m_soft_nofp_size",
                "armv8.1m.main_hard_fp_nomve_pacret_bti_exn_rtti_size",
                "armv8.1m.main_hard_fp_nomve_pacret_bti_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_fp_nomve_pacret_bti_size",
                "armv8.1m.main_hard_fp_nomve_pacret_bti_unaligned_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_exn_rtti_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_unaligned_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_exn_rtti_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_unaligned_size",
                "armv8.1m.main_soft_nofp_nomve_pacret_bti_exn_rtti_size",
                "armv8.1m.main_soft_nofp_nomve_pacret_bti_exn_rtti_unaligned_size",
                "armv8.1m.main_soft_nofp_nomve_pacret_bti_size",
                "armv8.1m.main_soft_nofp_nomve_pacret_bti_unaligned_size",
            ],
            description="rateInHz port not connected in Corstone-310 FVP (SDDKW-95688).",
        ),
        XFail(
            name="string push back",
            testnames=[
                "std/strings/basic.string/string.modifiers/string_append/push_back.pass.cpp",
            ],
            result=NewResult.XFAILED,
            project="libcxx",
            variants=[
                "armv7m_hard_fpv5_d16_exn_rtti_unaligned_size",
                "armv7m_hard_fpv5_d16_unaligned_size",
            ],
            description="push_back crashes on a basic_string with an oversized value type",
        ),
        XFail(
            name="picolibc_serial_test",
            testnames=[
                "test-hello-raw.test",
                "test-hello-raw-no-flash.test",
            ],
            result=NewResult.EXCLUDE,
            project="picolibc",
            variants=[
                "aarch64a_exn_rtti_unaligned",
                "aarch64a_soft_nofp",
                "aarch64a_soft_nofp_exn_rtti",
                "aarch64a_unaligned",
            ],
            description="The test expects serial port activity to end the test and times out without it.",
        ),
        XFail(
            name="Untriaged llvmlibc xfails 1",
            testnames=[
                "src/__support/CPP/libc.test.src.__support.CPP.simd_test.__hermetic__.__build__",
                "src/__support/CPP/libc.test.src.__support.CPP.string_test.__hermetic__.__build__",
                "src/stdio/libc.test.src.stdio.asprintf_test.__hermetic__.__build__",
                "src/stdio/libc.test.src.stdio.snprintf_test.__hermetic__.__build__",
                "src/stdio/libc.test.src.stdio.vasprintf_test.__hermetic__.__build__",
                "src/stdio/libc.test.src.stdio.vsnprintf_test.__hermetic__.__build__",
                "src/string/libc.test.src.string.memset_explicit_test.__hermetic__.__build__",
                "src/string/libc.test.src.string.memset_opt_host_test.__hermetic__.__build__",
                "src/string/libc.test.src.string.memset_test.__hermetic__.__build__",
                "src/time/libc.test.src.time.strftime_test.__hermetic__.__build__",
            ],
            result=NewResult.XFAILED,
            project="llvmlibc",
            variants=[
                "armebv7m_hard_fpv4_sp_d16_exn_rtti_size",
                "armebv7m_hard_fpv4_sp_d16_size",
                "armebv7m_soft_fpv4_sp_d16_exn_rtti_size",
                "armebv7m_soft_fpv4_sp_d16_size",
                "armebv7m_soft_nofp_exn_rtti_size",
                "armebv7m_soft_nofp_size",
            ],
            description="TODO: Unknown failures to be triaged.",
        ),
        XFail(
            name="Untriaged llvmlibc xfails 2",
            testnames=[
                "src/__support/libc.test.src.__support.arg_list_test.__hermetic__.__build__",
            ],
            result=NewResult.XFAILED,
            project="llvmlibc",
            variants=[
                "armv8.1m.main_hard_nofp_mve_exn_rtti_size",
                "armv8.1m.main_hard_nofp_mve_exn_rtti_unaligned",
                "armv8.1m.main_hard_nofp_mve_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_exn_rtti_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_unaligned_size",
                "armv8.1m.main_hard_nofp_mve_size",
                "armv8.1m.main_hard_nofp_mve_unaligned",
                "armv8.1m.main_hard_nofp_mve_unaligned_size",
            ],
            description="TODO: Unknown failures to be triaged.",
        ),
        XFail(
            name="Untriaged llvmlibc xfails 3",
            testnames=[
                "src/math/smoke/libc.test.src.math.smoke.cbrt_test.__hermetic__.__build__",
                "src/math/smoke/libc.test.src.math.smoke.exp10_test.__hermetic__.__build__",
                "src/math/smoke/libc.test.src.math.smoke.log10_test.__hermetic__.__build__",
            ],
            result=NewResult.XFAILED,
            project="llvmlibc",
            variants=[
                "aarch64a",
                "aarch64a_exn_rtti",
                "aarch64a_exn_rtti_unaligned",
                "aarch64a_unaligned",
                "aarch64r",
                "aarch64r_exn_rtti",
                "armv7a_hard_vfpv3_d16",
                "armv7a_hard_vfpv3_d16_exn_rtti",
                "armv7a_hard_vfpv3_d16_exn_rtti_unaligned",
                "armv7a_hard_vfpv3_d16_unaligned",
                "armv7a_soft_vfpv3_d16",
                "armv7a_soft_vfpv3_d16_exn_rtti",
                "armv7a_soft_vfpv3_d16_exn_rtti_unaligned",
                "armv7a_soft_vfpv3_d16_unaligned",
                "armv7m_hard_fpv5_d16_exn_rtti_unaligned_size",
                "armv7m_hard_fpv5_d16_unaligned_size",
                "armv7r_hard_vfpv3_d16",
                "armv7r_hard_vfpv3_d16_exn_rtti",
                "armv7r_hard_vfpv3_d16_exn_rtti_unaligned",
                "armv7r_hard_vfpv3_d16_unaligned",
                "armv8.1m.main_hard_fpdp_nomve_exn_rtti_unaligned",
                "armv8.1m.main_hard_fpdp_nomve_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_exn_rtti_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_unaligned_size",
                "armv8.1m.main_hard_fpdp_nomve_unaligned",
                "armv8.1m.main_hard_fpdp_nomve_unaligned_size",
            ],
            description="TODO: Unknown failures to be triaged.",
        ),
        XFail(
            name="Untriaged llvmlibc xfails 4",
            testnames=[
                "src/math/smoke/libc.test.src.math.smoke.ddivl_test.__hermetic__.__build__",
                "src/math/smoke/libc.test.src.math.smoke.dmull_test.__hermetic__.__build__",
            ],
            result=NewResult.XFAILED,
            project="llvmlibc",
            variants=[
                "armebv7m_hard_fpv4_sp_d16_exn_rtti_size",
                "armebv7m_hard_fpv4_sp_d16_size",
                "armebv7m_soft_fpv4_sp_d16_exn_rtti_size",
                "armebv7m_soft_fpv4_sp_d16_size",
                "armv7m_hard_fpv4_sp_d16_exn_rtti_size",
                "armv7m_hard_fpv4_sp_d16_exn_rtti_unaligned_size",
                "armv7m_hard_fpv4_sp_d16_size",
                "armv7m_hard_fpv4_sp_d16_unaligned_size",
                "armv7m_soft_fpv4_sp_d16_exn_rtti_size",
                "armv7m_soft_fpv4_sp_d16_exn_rtti_unaligned_size",
                "armv7m_soft_fpv4_sp_d16_size",
                "armv7m_soft_fpv4_sp_d16_unaligned_size",
                "armv7r_hard_vfpv3xd",
                "armv7r_hard_vfpv3xd_exn_rtti",
                "armv7r_hard_vfpv3xd_exn_rtti_unaligned",
                "armv7r_hard_vfpv3xd_unaligned",
                "armv7r_soft_vfpv3xd",
                "armv7r_soft_vfpv3xd_exn_rtti",
                "armv7r_soft_vfpv3xd_exn_rtti_unaligned",
                "armv7r_soft_vfpv3xd_unaligned",
                "armv8.1m.main_hard_fp_nomve_exn_rtti_unaligned",
                "armv8.1m.main_hard_fp_nomve_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_fp_nomve_pacret_bti_exn_rtti_size",
                "armv8.1m.main_hard_fp_nomve_pacret_bti_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_fp_nomve_pacret_bti_size",
                "armv8.1m.main_hard_fp_nomve_pacret_bti_unaligned_size",
                "armv8.1m.main_hard_fp_nomve_unaligned",
                "armv8.1m.main_hard_fp_nomve_unaligned_size",
                "armv8m.main_hard_fp_exn_rtti_unaligned_size",
                "armv8m.main_hard_fp_unaligned_size",
            ],
            description="TODO: Unknown failures to be triaged.",
        ),
        XFail(
            name="Untriaged llvmlibc xfails 5",
            testnames=[
                "src/stdlib/libc.test.src.stdlib.malloc_test.__hermetic__.__build__",
            ],
            result=NewResult.EXCLUDE,
            project="llvmlibc",
            variants=[
                "aarch64a",
                "aarch64a_exn_rtti",
                "aarch64r",
                "aarch64r_exn_rtti",
            ],
            description="TODO: Unknown failures to be triaged. These timeout rather than fail.",
        ),
        XFail(
            name="Untriaged llvmlibc xfails 6",
            testnames=[
                "src/math/smoke/libc.test.src.math.smoke.exp10m1f_test.__hermetic__.__build__",
                "src/stdlib/libc.test.src.stdlib.malloc_test.__hermetic__.__build__",
            ],
            result=NewResult.XFAILED,
            project="llvmlibc",
            variants=[
                "aarch64a",
                "aarch64a_exn_rtti",
                "aarch64a_exn_rtti_unaligned",
                "aarch64a_unaligned",
                "aarch64r",
                "aarch64r_exn_rtti",
                "armebv7m_hard_fpv4_sp_d16_exn_rtti_size",
                "armebv7m_hard_fpv4_sp_d16_size",
                "armebv7m_soft_fpv4_sp_d16_exn_rtti_size",
                "armebv7m_soft_fpv4_sp_d16_size",
                "armebv7m_soft_nofp_exn_rtti_size",
                "armebv7m_soft_nofp_size",
                "armv7a_hard_vfpv3_d16",
                "armv7a_hard_vfpv3_d16_exn_rtti",
                "armv7a_hard_vfpv3_d16_exn_rtti_unaligned",
                "armv7a_hard_vfpv3_d16_unaligned",
                "armv7a_soft_nofp",
                "armv7a_soft_nofp_exn_rtti",
                "armv7a_soft_nofp_exn_rtti_unaligned",
                "armv7a_soft_nofp_unaligned",
                "armv7a_soft_vfpv3_d16",
                "armv7a_soft_vfpv3_d16_exn_rtti",
                "armv7a_soft_vfpv3_d16_exn_rtti_unaligned",
                "armv7a_soft_vfpv3_d16_unaligned",
                "armv7m_hard_fpv4_sp_d16_exn_rtti_size",
                "armv7m_hard_fpv4_sp_d16_exn_rtti_unaligned_size",
                "armv7m_hard_fpv4_sp_d16_size",
                "armv7m_hard_fpv4_sp_d16_unaligned_size",
                "armv7m_hard_fpv5_d16_exn_rtti_unaligned_size",
                "armv7m_hard_fpv5_d16_unaligned_size",
                "armv7m_soft_fpv4_sp_d16_exn_rtti_size",
                "armv7m_soft_fpv4_sp_d16_exn_rtti_unaligned_size",
                "armv7m_soft_fpv4_sp_d16_size",
                "armv7m_soft_fpv4_sp_d16_unaligned_size",
                "armv7m_soft_nofp_exn_rtti_size",
                "armv7m_soft_nofp_exn_rtti_unaligned_size",
                "armv7m_soft_nofp_size",
                "armv7m_soft_nofp_unaligned_size",
                "armv7r_hard_vfpv3_d16",
                "armv7r_hard_vfpv3_d16_exn_rtti",
                "armv7r_hard_vfpv3_d16_exn_rtti_unaligned",
                "armv7r_hard_vfpv3_d16_unaligned",
                "armv7r_hard_vfpv3xd",
                "armv7r_hard_vfpv3xd_exn_rtti",
                "armv7r_hard_vfpv3xd_exn_rtti_unaligned",
                "armv7r_hard_vfpv3xd_unaligned",
                "armv7r_soft_nofp",
                "armv7r_soft_nofp_exn_rtti",
                "armv7r_soft_nofp_exn_rtti_unaligned",
                "armv7r_soft_nofp_unaligned",
                "armv7r_soft_vfpv3xd",
                "armv7r_soft_vfpv3xd_exn_rtti",
                "armv7r_soft_vfpv3xd_exn_rtti_unaligned",
                "armv7r_soft_vfpv3xd_unaligned",
                "armv8.1m.main_hard_fp_nomve_exn_rtti_unaligned",
                "armv8.1m.main_hard_fp_nomve_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_fp_nomve_pacret_bti_exn_rtti_size",
                "armv8.1m.main_hard_fp_nomve_pacret_bti_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_fp_nomve_pacret_bti_size",
                "armv8.1m.main_hard_fp_nomve_pacret_bti_unaligned_size",
                "armv8.1m.main_hard_fp_nomve_unaligned",
                "armv8.1m.main_hard_fp_nomve_unaligned_size",
                "armv8.1m.main_hard_fpdp_nomve_exn_rtti_unaligned",
                "armv8.1m.main_hard_fpdp_nomve_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_exn_rtti_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_unaligned_size",
                "armv8.1m.main_hard_fpdp_nomve_unaligned",
                "armv8.1m.main_hard_fpdp_nomve_unaligned_size",
                "armv8.1m.main_hard_nofp_mve_exn_rtti_size",
                "armv8.1m.main_hard_nofp_mve_exn_rtti_unaligned",
                "armv8.1m.main_hard_nofp_mve_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_exn_rtti_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_unaligned_size",
                "armv8.1m.main_hard_nofp_mve_size",
                "armv8.1m.main_hard_nofp_mve_unaligned",
                "armv8.1m.main_hard_nofp_mve_unaligned_size",
                "armv8.1m.main_soft_nofp_nomve_exn_rtti_unaligned_size",
                "armv8.1m.main_soft_nofp_nomve_pacret_bti_exn_rtti_size",
                "armv8.1m.main_soft_nofp_nomve_pacret_bti_exn_rtti_unaligned_size",
                "armv8.1m.main_soft_nofp_nomve_pacret_bti_size",
                "armv8.1m.main_soft_nofp_nomve_pacret_bti_unaligned_size",
                "armv8.1m.main_soft_nofp_nomve_unaligned_size",
                "armv8m.main_hard_fp_exn_rtti_unaligned_size",
                "armv8m.main_hard_fp_unaligned_size",
                "armv8m.main_soft_nofp_exn_rtti_unaligned_size",
                "armv8m.main_soft_nofp_unaligned_size",
            ],
            description="TODO: Unknown failures to be triaged.",
        ),
        XFail(
            name="Untriaged llvmlibc xfails 7",
            testnames=[
                "src/math/smoke/libc.test.src.math.smoke.fabsf16_test.__hermetic__.__build__",
                "src/math/smoke/libc.test.src.math.smoke.fmaxf16_test.__hermetic__.__build__",
                "src/math/smoke/libc.test.src.math.smoke.fmaximum_numf16_test.__hermetic__.__build__",
                "src/math/smoke/libc.test.src.math.smoke.fmaximumf16_test.__hermetic__.__build__",
                "src/math/smoke/libc.test.src.math.smoke.fminf16_test.__hermetic__.__build__",
                "src/math/smoke/libc.test.src.math.smoke.fminimum_numbf16_test.__hermetic__.__build__",
                "src/math/smoke/libc.test.src.math.smoke.fminimum_numf16_test.__hermetic__.__build__",
                "src/math/smoke/libc.test.src.math.smoke.fminimumf16_test.__hermetic__.__build__",
            ],
            result=NewResult.EXCLUDE,
            project="llvmlibc",
            variants=[
                "aarch64a",
                "aarch64a_exn_rtti",
            ],
            description="TODO: Unknown failures to be triaged. These timeout rather than fail.",
        ),
        XFail(
            name="Untriaged llvmlibc xfails 8",
            testnames=[
                "src/math/smoke/libc.test.src.math.smoke.fabsf16_test.__hermetic__.__build__",
                "src/math/smoke/libc.test.src.math.smoke.fmaxf16_test.__hermetic__.__build__",
                "src/math/smoke/libc.test.src.math.smoke.fmaximum_numf16_test.__hermetic__.__build__",
                "src/math/smoke/libc.test.src.math.smoke.fmaximumf16_test.__hermetic__.__build__",
                "src/math/smoke/libc.test.src.math.smoke.fminf16_test.__hermetic__.__build__",
                "src/math/smoke/libc.test.src.math.smoke.fminimum_numbf16_test.__hermetic__.__build__",
                "src/math/smoke/libc.test.src.math.smoke.fminimum_numf16_test.__hermetic__.__build__",
                "src/math/smoke/libc.test.src.math.smoke.fminimumf16_test.__hermetic__.__build__",
            ],
            result=NewResult.XFAILED,
            project="llvmlibc",
            variants=[
                "aarch64a_exn_rtti_unaligned",
                "aarch64a_unaligned",
            ],
            description="TODO: Unknown failures to be triaged.",
        ),
        XFail(
            name="Untriaged llvmlibc xfails 9",
            testnames=[
                "src/math/smoke/libc.test.src.math.smoke.fmaf_test.__hermetic__.__build__",
            ],
            result=NewResult.XFAILED,
            project="llvmlibc",
            variants=[
                "armv7r_hard_vfpv3xd",
                "armv7r_hard_vfpv3xd_exn_rtti",
                "armv7r_hard_vfpv3xd_exn_rtti_unaligned",
                "armv7r_hard_vfpv3xd_unaligned",
                "armv7r_soft_vfpv3xd",
                "armv7r_soft_vfpv3xd_exn_rtti",
                "armv7r_soft_vfpv3xd_exn_rtti_unaligned",
                "armv7r_soft_vfpv3xd_unaligned",
            ],
            description="TODO: Unknown failures to be triaged.",
        ),
        XFail(
            name="Untriaged llvmlibc xfails 10",
            testnames=[
                "src/math/smoke/libc.test.src.math.smoke.llrint_test.__hermetic__.__build__",
                "src/math/smoke/libc.test.src.math.smoke.llrintbf16_test.__hermetic__.__build__",
                "src/math/smoke/libc.test.src.math.smoke.llrintf_test.__hermetic__.__build__",
                "src/math/smoke/libc.test.src.math.smoke.llrintl_test.__hermetic__.__build__",
                "src/math/smoke/libc.test.src.math.smoke.lrint_test.__hermetic__.__build__",
                "src/math/smoke/libc.test.src.math.smoke.lrintbf16_test.__hermetic__.__build__",
                "src/math/smoke/libc.test.src.math.smoke.lrintf_test.__hermetic__.__build__",
                "src/math/smoke/libc.test.src.math.smoke.lrintl_test.__hermetic__.__build__",
            ],
            result=NewResult.XFAILED,
            project="llvmlibc",
            variants=[
                "armebv7m_soft_nofp_exn_rtti_size",
                "armebv7m_soft_nofp_size",
                "armv7a_soft_nofp",
                "armv7a_soft_nofp_exn_rtti",
                "armv7a_soft_nofp_exn_rtti_unaligned",
                "armv7a_soft_nofp_unaligned",
                "armv7m_soft_nofp_exn_rtti_size",
                "armv7m_soft_nofp_exn_rtti_unaligned_size",
                "armv7m_soft_nofp_size",
                "armv7m_soft_nofp_unaligned_size",
                "armv7r_soft_nofp",
                "armv7r_soft_nofp_exn_rtti",
                "armv7r_soft_nofp_exn_rtti_unaligned",
                "armv7r_soft_nofp_unaligned",
                "armv8.1m.main_hard_nofp_mve_exn_rtti_size",
                "armv8.1m.main_hard_nofp_mve_exn_rtti_unaligned",
                "armv8.1m.main_hard_nofp_mve_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_exn_rtti_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_size",
                "armv8.1m.main_hard_nofp_mve_pacret_bti_unaligned_size",
                "armv8.1m.main_hard_nofp_mve_size",
                "armv8.1m.main_hard_nofp_mve_unaligned",
                "armv8.1m.main_hard_nofp_mve_unaligned_size",
                "armv8.1m.main_soft_nofp_nomve_exn_rtti_unaligned_size",
                "armv8.1m.main_soft_nofp_nomve_pacret_bti_exn_rtti_size",
                "armv8.1m.main_soft_nofp_nomve_pacret_bti_exn_rtti_unaligned_size",
                "armv8.1m.main_soft_nofp_nomve_pacret_bti_size",
                "armv8.1m.main_soft_nofp_nomve_pacret_bti_unaligned_size",
                "armv8.1m.main_soft_nofp_nomve_unaligned_size",
                "armv8m.main_soft_nofp_exn_rtti_unaligned_size",
                "armv8m.main_soft_nofp_unaligned_size",
            ],
            description="TODO: Unknown failures to be triaged.",
        ),
        XFail(
            name="Untriaged llvmlibc xfails 11",
            testnames=[
                "src/math/smoke/libc.test.src.math.smoke.logf_test.__hermetic__.__build__",
            ],
            result=NewResult.XFAILED,
            project="llvmlibc",
            variants=[
                "aarch64a",
                "aarch64a_exn_rtti",
                "aarch64a_exn_rtti_unaligned",
                "aarch64a_unaligned",
                "aarch64r",
                "aarch64r_exn_rtti",
                "armv7m_hard_fpv5_d16_exn_rtti_unaligned_size",
                "armv7m_hard_fpv5_d16_unaligned_size",
                "armv8.1m.main_hard_fpdp_nomve_exn_rtti_unaligned",
                "armv8.1m.main_hard_fpdp_nomve_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_exn_rtti_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_exn_rtti_unaligned_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_size",
                "armv8.1m.main_hard_fpdp_nomve_pacret_bti_unaligned_size",
                "armv8.1m.main_hard_fpdp_nomve_unaligned",
                "armv8.1m.main_hard_fpdp_nomve_unaligned_size",
            ],
            description="TODO: Unknown failures to be triaged.",
        ),
    ]

    tests_to_xfail = []
    tests_to_upass = []
    tests_to_exclude = []

    for xfail in xfails:
        if args.project != xfail.project:
            continue
        if xfail.variants is not None:
            if args.variant is None:
                raise ValueError(
                    f"--variant must be specified for project {args.project}"
                )
            if args.variant not in xfail.variants:
                continue
        if xfail.conditional is not None:
            if not xfail.conditional():
                continue
        if xfail.result == NewResult.XFAILED:
            tests_to_xfail.extend(xfail.testnames)
        elif xfail.result == NewResult.PASSED:
            tests_to_upass.extend(xfail.testnames)
        elif xfail.result == NewResult.EXCLUDE:
            tests_to_exclude.extend(xfail.testnames)

    tests_to_xfail.sort()
    tests_to_upass.sort()
    tests_to_exclude.sort()

    if args.output_args:
        os.makedirs(os.path.dirname(args.output_args), exist_ok=True)
        with open(args.output_args, "w", encoding="utf-8") as f:
            if len(tests_to_xfail) > 0:
                # --xfail and --xfail-not expect a comma separated list of test names.
                f.write("--xfail=")
                f.write(";".join(tests_to_xfail))
                f.write("\n")
            if len(tests_to_upass) > 0:
                f.write("--xfail-not=")
                f.write(";".join(tests_to_upass))
                f.write("\n")
            if len(tests_to_exclude) > 0:
                # --filter-out expects a regular expression to match any test names.
                escaped_testnames = [
                    re.escape(testname) for testname in tests_to_exclude
                ]
                f.write("--filter-out=")
                f.write("|".join(escaped_testnames))
                f.write("\n")
        print(f"xfail list written to {args.output_args}")
    else:
        if len(tests_to_xfail) > 0:
            print("xfailed tests:")
            for testname in tests_to_xfail:
                print(testname)
        if len(tests_to_upass) > 0:
            print("xfail removed from tests:")
            for testname in tests_to_upass:
                print(testname)
        if len(tests_to_exclude) > 0:
            print("excluded tests:")
            for testname in tests_to_exclude:
                print(testname)


if __name__ == "__main__":
    main()
